name: Secrets

on:
  workflow_dispatch:
    inputs:
       TEST_SECRET:
        type: string
        description: TEST_SECRET

       ANOTHER_SECRET:
        type: string
        description: ANOTHER_SECRET

jobs:
  update-secrets:
    runs-on: ubuntu-latest
  
    strategy:
      matrix:
        secret_name: ["TEST_SECRET", "ANOTHER_SECRET"]

    steps:
      - run: gh secrets list
        if: ${{ inputs[matrix.secret_name] != '' }}
        env:
          SECRET_NAME: matrix.secret_name
          SECRET_VALUE: ${{ inputs[matrix.secret_name] }}
