# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:
    inputs:
       TEST_SECRET:
        type: string
        description: TEST_SECRET

       ANOTHER_SECRET:
        type: string
        description: ANOTHER_SECRET

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update-secrets:
    runs-on: ubuntu-latest
  
    strategy:
      matrix:
        secret_names: ["test", "another"]

    steps:
      - run: gh secrets list
        env:
          SECRET_NAME: TEST_SECRET
          SECRET_VALUE: ${{ inputs.TEST_SECRET }}
