name: Secrets

on:
  workflow_dispatch:
    inputs:
       TEST_SECRET:
        type: string
        description: TEST_SECRET

       ANOTHER_SECRET:
        type: string
        description: ANOTHER_SECRET

jobs:
  get-secrets-to-update:
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.set_matrix.outputs.matrix }}

    steps:
      - name: Set matrix
        id: set_matrix
        run: |
          names=("TEST_SECRET" "ANOTHER_SECRET")
          names_to_update=()
          for i in ${names[@]}; do
            test -n $(jq -r ".inputs.$i" $GITHUB_EVENT_PATH) && names_to_update+=($i)
          done
          echo ${names_to_update[@]}

  update-secrets:
    runs-on: ubuntu-latest
  
    strategy:
      matrix:
        secret_name: ["TEST_SECRET", "ANOTHER_SECRET"]

    steps:
      - run: echo $SECRET_NAME is $SECRET_VALUE
        if: ${{ inputs[matrix.secret_name] != '' }}
        env:
          SECRET_NAME: matrix.secret_name
          SECRET_VALUE: ${{ inputs[matrix.secret_name] }}
